### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by MattiaDeiRossi** [neobotix/neo_docking#16]
Hi all, 

is there a version for ros2 of this pkg?

**Comment by padhupradheep** [comment]
Hey, at the moment we do already have a [neo_docking2](https://github.com/neobotix/neo_docking2), but that ROS 2 package does not use AR tags. We do not have plans to integrate AR tags in the ROS 2 version, rather we are planning to go all out on a much simpler approach for detection of the charging station and any other components that you probably might want to detect. 

Currently in the neo_docking2 package, there is no sort of automatic detection happening, rather it is a straight forward approach, where you specify the position of the docking station either manually or through the map. 

But if there is a requirement of AR tag detection at your end. We'll be all ears, and we can find out a possible solution that would be best fit for all the parties. I'm open for a call in case if you are interested in discussing further.
